# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b339337f2487d2cdd2d1545d868bba94e99d93f56f8684380cc62301abefba472efbc9ef1dd20c9b86fbfe56ad6579b6d31e31efd045052a7fd7f62da323812

test:
  secret_key_base: 185b02cb4911ce748e26017ffcc286dbb7f2f1bc0684187ccf3e07851a51d2ab25db89bb61d1ba67e7aa8dece3891e00b2c5d4321874c68878c0148279f2d223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
